# Generated by Django 2.1.7 on 2019-04-17 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_auto_20190417_1912'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='lecture',
            unique_together={('slug', 'course')},
        ),
    ]
