# Generated by Django 2.1.7 on 2019-04-17 22:01

import courses.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_auto_20190417_2200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='order',
            field=courses.fields.PositionField(default=-1),
        ),
    ]
