# Generated by Django 2.1.7 on 2019-04-17 22:21

import courses.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_auto_20190417_2201'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='category',
            field=models.CharField(choices=[('main', 'Main'), ('secondary', 'Secondary')], default='main', max_length=120),
        ),
        migrations.AddField(
            model_name='course',
            name='order',
            field=courses.fields.PositionField(default=-1),
        ),
    ]
