# Generated by Django 2.2 on 2019-04-24 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_mycourses'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mycourses',
            options={'verbose_name': 'My Courses', 'verbose_name_plural': 'My courses'},
        ),
    ]
