# Generated by Django 2.2 on 2019-04-28 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_category_video'),
        ('courses', '0014_auto_20190428_0643'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='secondary',
            field=models.ManyToManyField(blank=True, related_name='secondary_category', to='categories.Category'),
        ),
    ]
