# Generated by Django 2.2 on 2019-05-13 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0017_auto_20190429_2238'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='free',
            field=models.BooleanField(default=False),
        ),
    ]
