# Generated by Django 2.1.7 on 2019-04-03 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0004_video_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='free',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='video',
            name='member_required',
            field=models.BooleanField(default=False),
        ),
    ]
